title: IO
description: > # this means to ignore newlines until "baseurl:"
  Personal Blog.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: "" #if your site has a twitter account, enter it here

# Author Settings
author: Lucas Dau # add your name
author-img: heisen.jpg # add your photo
about-author: Graduando em Eng. de Computação - ICEA|UFOP # add description

github: dfslucas # add your Github handle
linkedin: lucasdau # add your Linkedin handle
email: lucas.dau@hotmail.com # add your Email address

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

theme: jekyll-theme-architect